### ISSUE TITLE
SmartWaypoints\SmartWaypoints.lua:145: bad argument #1 to 'setmetatable' (table expected, got nil) on login

### ISSUE THREAD

**Issue by tordenflesk** [bloerwald/SmartWaypoints#2]
2x SmartWaypoints\SmartWaypoints.lua:145: bad argument #1 to 'setmetatable' (table expected, got nil)
[C]: in function `setmetatable'
SmartWaypoints\SmartWaypoints.lua:145: in function `initialize_localization'
SmartWaypoints\SmartWaypoints.lua:249: in function `ADDON_LOADED'
SmartWaypoints\SmartWaypoints.lua:262: in function <SmartWaypoints\SmartWaypoints.lua:260>

Locals:
(*temporary) = nil
(*temporary) = <table> {
 __index = <function> defined @SmartWaypoints\SmartWaypoints.lua:146
}
(*temporary) = "table expected, got nil"

**Comment by bloerwald** [comment]
You are my first non-german-or-english user. Congratulations! 

Trivial fix: in line 145, add `or {}` within the first argument: `  self.L = setmetatable (Ls[GetLocale()] or {}, {`, I feel bad for not thinking about that. 

I'll ship a new build in a few minutes. If you want to be a lovely user, would you mind translating for your locale? It requires the following phrases (where `{xxx}` is a placeholder in the phrase:

- `Travel suggestion: {take portal x}`
- `Reach {final destination}`
- `Changed mode: {new working mode}`
- `Unknown mode: {user entered string} (known: {existing modes})`
- `current mode: {current mode}`
- `Unknown target`
- `Never show any waypoints`
- `Mark waypoints as suggestions`
- `Show only the target to reach, no suggestions`
- `Use Blizzard behavior`
- `help` as in the command to use for getting help
- `cycle between available modes`
- if `{mode description} ({short mode name})` is a bad way to express modes in a list in the locale, an alternative format for 

Regardless of if you have the time for that, thank you very much for the report!

**Comment by tordenflesk** [comment]
I'm 99% sure I'm on the EU English client.

**Comment by bloerwald** [comment]
Oof. I pushed the should-be-fix, which should also work for you.

Can you give me the `/dump GetLocale()` output? I was expecting it to be `enGB`.

**Comment by tordenflesk** [comment]
Yeah, I just got enUS. I'm playing on EU realms though. Weird.

-Espen
